services:
  rag-assistant:
    build: .
    container_name: rag-assistant
    volumes:
      - faiss_data:/app/faiss_index
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    ports:
      - "8501:8501"

volumes:
  faiss_data:
